# Generated by Django 4.2.11 on 2024-06-03 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_watchlist_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='timestamp',
        ),
    ]
